In [3]:
import numpy as np

arr = np.random.randint(1,100, size=(10,5)) # sample 10 feature 5

print(arr.shape)

(10, 5)


In [4]:
b = arr.reshape(5,10)

print(b.shape)
print(b.ndim)
print(b)

(5, 10)
2
[[ 9 51 44 18 60 12 90 26 40 68]
 [71 43 97  9 48 78 18 71 73 43]
 [92 36 78  7 75 32 86 89 50 46]
 [ 4 27  5 66 17 24 82 88 62 95]
 [96 41 12 77 53 94 58  4 29 57]]


In [7]:
flatten = b.flatten()
print(flatten.ndim)

column_wise_flattening = np.ravel(b,order='C')
column_wise_flattening

1


array([ 9, 51, 44, 18, 60, 12, 90, 26, 40, 68, 71, 43, 97,  9, 48, 78, 18,
       71, 73, 43, 92, 36, 78,  7, 75, 32, 86, 89, 50, 46,  4, 27,  5, 66,
       17, 24, 82, 88, 62, 95, 96, 41, 12, 77, 53, 94, 58,  4, 29, 57],
      dtype=int32)

In [8]:
a = np.random.randint(1,10, size=(2,3))
b = np.random.randint(20,30, size=(2,3))
print(a)
print("-"*30)
print(b)

[[6 7 7]
 [8 5 4]]
------------------------------
[[23 27 24]
 [27 23 21]]


### concatenate

In [10]:
con_row = np.concatenate((a,b), axis=0) # 0 => row wise
print(con_row)
print("-"*30)
con_col = np.concatenate((a,b),axis=1)
print(con_col)

[[ 6  7  7]
 [ 8  5  4]
 [23 27 24]
 [27 23 21]]
------------------------------
[[ 6  7  7 23 27 24]
 [ 8  5  4 27 23 21]]


In [13]:
#error

# in row wise concatenation two matix should have the same number of column
# in column wise concatenation two matix should have the same number of rows

x = np.random.randint(1,10, size = (2,3))
y = np.random.randint(1,10, size = (1,3))

r = np.concatenate((x,y), axis=0)
r = np.concatenate((x,y), axis=1)

print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [14]:
# transpose 

mat = np.array([[10,20,30],
                [30,40,50]
               ])
transpose = mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [21]:
# array split 
a = np.random.randint(1,10, size = (10, ) )
print(a)

splitted_array = np.array_split(a,3)
print(splitted_array)


# split should have the equal division
a = np.random.randint(1,10, size = (9, ) )
splitted_array = np.split(a,3)
print(splitted_array)

[9 4 9 6 3 2 3 7 7 1]
[array([9, 4, 9, 6], dtype=int32), array([3, 2, 3], dtype=int32), array([7, 7, 1], dtype=int32)]
[array([1, 9, 8], dtype=int32), array([5, 5, 5], dtype=int32), array([5, 6, 7], dtype=int32)]


### arithmetic operator and mathematical functions


In [28]:
# faster for vectorization
x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]


In [29]:
# mathematical function 
# trigonometry 
# sin , cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

deg_rad = np.deg2rad(x)
print(deg_rad)

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]
[0.17453293 0.13962634 0.52359878 1.74532925]


In [32]:
#log 

x = np.array([10,8,16,100])
base_10_log_val = np.log10(x)

print(base_10_log_val)

base_2_log_val = np.log2(x)
print(base_2_log_val)

sqrt = np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [35]:
# different 
s = np.sum(x)
print(s)


#prefix sum 
cumulative_sum = np.cumulative_sum(x)
print(cumulative_sum)

134
[ 10  18  34 134]


In [40]:
#broadcasting 
x = np.array([ 10 , 8 , 16 , 100 ])

res = x+2
print(res)

print("-"*30)
#rulings = columns er size and vector er size same hote hobe 
matrix = np.array([[10,20,30],
                [30,40,50]
               ])

res = matrix+2
print(res)

print("-"*30)

# row size and column size must be same for operations
vector = np.array([1,2,3]) 
res = matrix + vector
print(res) 

[ 12  10  18 102]
------------------------------
[[12 22 32]
 [32 42 52]]
------------------------------
[[11 22 33]
 [31 42 53]]


### Logical Function

In [47]:
# comparison - >,< , >= ,<= , == , !=
x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y 

print(greater_than)

equal = x == y
print(equal)

# all() -> if all are true or not 
# any() -> if any of it is true

print(np.all(greater_than))
print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


### Sorting

In [50]:

#inplace 
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()
print(z)

z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [54]:
# copy sorting
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [58]:
# 2d array sorting 
mat = np.array([[10,3,5],[8,4,9]])
print(mat)

print("-"*30)

# horizontal axis = 1
horizontal_sort = np.sort(mat, axis=1)
print(horizontal_sort)

print("-"*30)
vertical_sort = np.sort(mat, axis=0)
print(vertical_sort)

[[10  3  5]
 [ 8  4  9]]
------------------------------
[[ 3  5 10]
 [ 4  8  9]]
------------------------------
[[ 8  3  5]
 [10  4  9]]


### Searching

In [59]:
print(x)

[ 10   8  16 100]


In [62]:
# np.where( condition , x , y ) if true x , otherwise replace with y 
idx = np.where(x==8) # returns index

print(idx)
arr = np.where(x>8,x, 0)
print(arr)

(array([1]),)
[ 10   0  16 100]


In [63]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [65]:
idx = np.where(mat>8) # returns index
print(idx)

arr = np.where(mat > 8, mat, 0) # returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [66]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x) 
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


### counting in ndarray


In [67]:
a = np.random.randint(1,100, size = (100, ))
print(a)

[79 86 40 25 58  4 43 10 62 97 77 71 94 51 96 23 63 99 97 93 71 88 22 29
  8 92 18 25 84 91 71  3 40 93 41 94 51 29  8 55 60 74 48 99 96 15 22 96
 69 57  3 59 23  6 57 32  2 52 43 66 21 51 77 41 10 76 48 34 18 62 66 56
 76 72 70 80 35 26 53 21 84 28 21 81 65 34 27 31 14 27 26 75 11 15 61 51
 47 12  5 93]


In [75]:
value_greater_than = np.count_nonzero(a == 99)
print(value_greater_than)

2


In [80]:
unique_value,counts = np.unique(a,return_counts=True)
print(unique_value)
print(counts)

[ 2  3  4  5  6  8 10 11 12 14 15 18 21 22 23 25 26 27 28 29 31 32 34 35
 40 41 43 47 48 51 52 53 55 56 57 58 59 60 61 62 63 65 66 69 70 71 72 74
 75 76 77 79 80 81 84 86 88 91 92 93 94 96 97 99]
[1 2 1 1 1 2 2 1 1 1 2 2 3 2 2 2 2 2 1 2 1 1 2 1 2 2 2 1 2 4 1 1 1 1 2 1 1
 1 1 2 1 1 2 1 1 3 1 1 1 2 2 1 1 1 2 1 1 1 1 3 2 3 2 2]


### statistical function


In [83]:
data = np.genfromtxt('students_marks.csv',delimiter=',',skip_header=1)
print(data)

[[45. 45. 45.]
 [45. 98. 98.]
 [23. 23. 23.]
 [45. 45. 45.]
 [98. 98. 98.]
 [97. 97. 97.]
 [87. 87. 87.]
 [88. 88. 88.]]


In [90]:
math_marks = data[::, :1]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation
std_math_marks = np.std(math_marks)
print(std_math_marks)

[[45. 45. 23. 45. 98. 97. 87. 88.]]
98.0
23.0
66.0
66.0
27.572631357924475


In [93]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)
print("Correlation matrix:\n", correlation)

Correlation matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


### linear algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])


# the row of a and the column of b should be same 
dot_product = np.dot(A,B)
print(dot_product)


# trace 
print(np.trace(B))


In [95]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])
det_of_sq = np.linalg.det(sq_mat)
print(det_of_sq)

rank_sq = np.linalg.matrix_rank(sq_mat)
print(rank_sq)

6.66133814775094e-16
2


In [96]:
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
